version: '3.4'

services:
  productdb:
    image: mongo

  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: src/Services/Product/Dockerfile

volumes:
  mongo_data:
